### ISSUE TITLE
Buffer in browser

### ISSUE THREAD

**Issue by CMCDragonkai** [browserify/randombytes#11]
The browser.js uses safe-buffer package as the implementation of Buffer.

However safe-buffer doesn't supply a browser polyfill for buffer, it just uses the Node buffer.

So how is browser.js going to work in browsers?

Shouldn't it instead use the Buffer polyfill? https://github.com/feross/buffer

**Comment by calvinmetcalf** [comment]
this is meant to be used with browserify or webpack which provide those buffers

**Comment by ayanamidev** [comment]
@calvinmetcalf Webpack 5 removed buffer so it should have a fallback https://github.com/webpack/changelog-v5/issues/10
