### ISSUE TITLE
how to shim randombytes?

### ISSUE THREAD

**Issue by pkit** [browserify/randombytes#20]
What is the proper way to shim/monkeypatch/replace this library?
I.e. I need to use my version of `randomBytes()` function for an exotic platform that is not supported.
Tried `browserify().external(['randombytes'])` it doesn't work: `error: Cannot find module 'randombytes'`.
Obviously my module `randombytes` is available, so the error is bogus.
And because browserify never produces any logs I have no idea what was included in the bundle and how exactly it searches for the module in question.

**Comment by dcousens** [comment]
I don't know if this question is in scope, and it's 4 years past
