### ISSUE TITLE
Remove buffer?

### ISSUE THREAD

**Issue by jimmywarting** [browserify/randombytes#25]
Could you make this less dependent on node stuff?

Would like to see a major update where Uint8Array is returned instead on both node and browser.
Buffer is unnecessary in many cases where it's just seen as a Uint8Array. And where many node core feature is more acceptable of typed arrays instead
So including Buffer (safe-buffer) in the browser is just bloated and unnecessary.

Think if ppl need a Buffer then they should use `Buffer.from(randombytes(1))` instead.

---

Can make a PR if you wish

**Comment by dcousens** [comment]
`safe-buffer` has been removed in https://github.com/browserify/randombytes/pull/27, I still need to determine exactly the extent to which that will have an impact on users in recent LTS versions of node and browsers

**Comment by dcousens** [comment]
I am

**Comment by dcousens** [comment]
@jimmywarting I understand your reasoning, but I don't think we want to broaden the scope of this package when it should always produce the same output and types as `node`.

Unfortunately this package is called `randombytes`, and not `@browserify/randombytes`, but, it's likely package scopes weren't available when the project started.
