### ISSUE TITLE
global is replaced by globalThis？

### ISSUE THREAD

**Issue by garmin21** [browserify/randombytes#29]
There is a problem with the global reference used in the source code, it may not exist, because it is a compatibility problem, why not use globalThis?

**Comment by justin0mcateer** [comment]
I ran into this problem and needed to patch the package due to lack of 'global' in the browser environment.

Here is the (hack) patch I used:
```diff
diff --git a/node_modules/randombytes/browser.js b/node_modules/randombytes/browser.js
index 0fb0b71..7dc0e6c 100644
--- a/node_modules/randombytes/browser.js
+++ b/node_modules/randombytes/browser.js
@@ -13,7 +13,9 @@ function oldBrowser () {
 }
 
 var Buffer = require('safe-buffer').Buffer
-var crypto = global.crypto || global.msCrypto
+// var crypto = global.crypto || global.msCrypto
+var crypto = globalThis.crypto || globalThis.msCrypto
+
 
 if (crypto && crypto.getRandomValues) {
   module.exports = randomBytes
```

**Comment by bneijt** [comment]
I think it makes sense to use globalThis if available and fall back to the injected global if required, so I created a PR to that effect.
